spring.application.name=maikeise-banking-simulator
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/maikeise}
spring.datasource.username=${DB_USER:maikeise}
spring.datasource.password=${DB_PASSWORD:maikeise_local_only}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.type.preferred_instant_jdbc_type=TIMESTAMP_WITH_TIMEZONE
